variables:
    DNS_ZONE:
        default: hack.cloudcoreo.com
        description: the dns entry for the zone (i.e. example.com)
        required: true
    VPC_NAME:
        required: true
        description: the name of the VPC
        default: test-vpc
    VPC_OCTETS:
        required: true
        description: the /16 net of the VPC to look for - i.e 123.123.0.0
        default: 10.11.0.0
    PRIVATE_ROUTE_NAME:
        required: true
        description: the name to give to the private route
        default: test-private-route
    PRIVATE_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the private vpc subnets
        default: test-private-subnet
    MONGO_SG_NAME:
        default: mongodb
        required: true
        description: the name of the mongodb security group to create
    MONGO_INGRESS_CIDRS:
        default:
            - 10.0.0.0/8
        description: cidrs to allow outgoing connections to
        required: true
        type: Array
    MONGO_EGRESS_CIDRS:
        default:
            - 0.0.0.0/0
        description: cidrs to allow outgoing connections to
        required: true
        type: Array
    BACKUP_BUCKET:
        default: cloudcoreo-backups
        description: what s3 bucket should we back up to?
        required: true
    MONGO_NAME:
        default: mongodb
        description: name this mongodb deployment
        required: true
    MONGO_SIZE:
        default: t2.micro
        description: null
        required: true
    MONGO_GROUP_SIZE_MIN:
        required: true
        description: the miniumum number of mongo instances to launch
        default: 1
        type: number
    MONGO_GROUP_SIZE_MAX:
        required: true
        description: the maximum number of mongo instances to launch
        default: 1
        type: number
    TIMEZONE:
        default: America/Chicago
        value: America/Chicago
        description: the timezone the servers should come up in
        overrides: null
        required: true
        type: null
    MONGO_BACKUP_CRON:
        default: "0 * * * *"
        description: the cron schedule for backups
        overrides: null
        required: true
        type: string
    MONGO_DB_VERSION:
        default: 3.2.5
        description: The mongodb version to install - only 3.2.x is supported right now
        required: true
    REGION:
        default: "INSTANCE::region"
        description: the region we are launching in
        overrides: null
        required: true
        type: string
    ENV:
        default: prod
        description: null
        overrides: null
        required: true
        type: null
    BACKUP_BUCKET_REGION:
        default: us-east-1
        description: the region where there vpn backups bucket was created
        overrides: null
        required: false
    MONGO_AMI:
        description: the ami id of the mongo db server
        switch: "INSTANCE::region"
        cases:
            us-east-1: ami-1ecae776
            us-west-1: ami-d114f295
            us-west-2: ami-e7527ed7
            eu-west-1: ami-a10897d6
            eu-central-1: ami-a8221fb5
            ap-southeast-1: ami-68d8e93a
            ap-northeast-1: ami-cbf90ecb
            ap-southeast-2: ami-fd9cecc7
            sa-east-1: ami-b52890a8
        type: case
    MONGO_KEY:
        default: macbook
        description: the key pair to launch the mongo db with - this should exist in the clou already
        required: false
        type: string
    DATADOG_KEY:
        default: b839afdc0371f3fcf97492cd1f03fdd9
        description: "If you have a datadog key, enter it here and we will install the agent"
        required: false
    MONGO_DATA_DIR:
        default: /data/db
        description: If you want the mongodb data dir to be something other than /data/db set it here
        required: true
    DATABASE_NAME:
        default: testdatabase
        description: null
        required: true
        type: string
    MASTER_USERNAME:
        default: testuser
        description: null
        required: true
        type: string
    MASTER_PASSWORD:
        default: testuser
        description: null
        required: true
        type: string
    CLUSTER_TYPE:
        default: ['Single Node', 'Replica Set', 'Sharded Cluster']
        description: Cluster type
        required: true
        type: Array<String>
    AVAILABILITY_ZONES:
        default: ['us-east-1b', 'us-east-1c', 'us-east-1d']
        description: Multiple availability zone
        required: true
        type: Array<String>
    NO_OF_REPLICA_SET:
        default: 1
        description: Number of replica set
        required: true
        type: number
